import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { organizationTypes } from '@/lib/db/schema';


// Generated by https://quicktype.io

export interface ErrorType {
  message: Message;
}

export interface Message {
  query:  string;
  params: string[];
  cause:  Cause;
}

export interface Cause {
  length:     number;
  name:       string;
  severity:   string;
  code:       string;
  detail:     string;
  schema:     string;
  table:      string;
  constraint: string;
  file:       string;
  line:       string;
  routine:    string;
}

export async function postOrganizationType(req: NextRequest) {
  try {
    const body = await req.json();
    const { name, description } = body;

    if (!name) {
      return NextResponse.json({ message: 'Name is required' }, { status: 400 });
    }

    const [organization] = await db.insert(organizationTypes).values({ name, description }).returning();
    return NextResponse.json({ data: organization,message: 'Organization type created successfully' }, { status: 201 });
  } catch (err) {
    console.log(err)
    return NextResponse.json({ message: 'Internal Server Error' }, { status: 500 });
  }
}

